### ISSUE TITLE
var identity_secret = config.accounts.first.identity_secret;

### ISSUE THREAD

**Issue by folvos** [agasking1337/steam-trade-idler#1]
TypeError: Cannot read property 'first' of undefined
    at E:\coding\workspace\trade\index.js:107:48
    at update (E:\coding\workspace\trade\node_modules\steam-tradeoffer-manager\l
ib\classes\TradeOffer.js:532:5)
    at manager.getOffer (E:\coding\workspace\trade\node_modules\steam-tradeoffer
-manager\lib\classes\TradeOffer.js:566:3)
    at Helpers.checkNeededDescriptions (E:\coding\workspace\trade\node_modules\s
team-tradeoffer-manager\lib\index.js:437:4)
    at Object.exports.checkNeededDescriptions (E:\coding\workspace\trade\node_mo
dules\steam-tradeoffer-manager\lib\helpers.js:90:3)
    at _apiCall (E:\coding\workspace\trade\node_modules\steam-tradeoffer-manager
\lib\index.js:431:11)
    at SteamCommunity._community.httpRequest (E:\coding\workspace\trade\node_mod
ules\steam-tradeoffer-manager\lib\webapi.js:61:3)
    at Request._callback (E:\coding\workspace\trade\node_modules\steamcommunity\
components\http.js:67:15)
    at Request.self.callback (E:\coding\workspace\trade\node_modules\request\req
uest.js:185:22)
    at emitTwo (events.js:126:13)

**Comment by folvos** [comment]
https://imgur.com/a/Aa1P6lt
